name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: echo "Installing dependencies..."
      - name: Run Tests
        run: echo "Tests Passed!"
      - name: Deploy to Kubernetes
  run: kubectl apply -f deployment.yaml
"
